version: "3.7"

services:
  demo:
    image: sba-cli/demo
    container_name: demo
    build:
      context: .
      dockerfile: ./demo-service/Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
