server:
  port: 8080

spring:
  application:
    name: demo-service
  profiles:
    active: dockerized

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
    metrics:
      enabled: true
    logfile:
      enabled: true
  metrics:
    tags:
      application: "${spring.application.name}"
  info:
    git.mode: FULL

info:
  title: demo-service

logging:
  file:
    name: logs/logfile.log
---
spring:
  profile:
    name: dockerized
